server:
  port: 8080  # Web application runs on port 8080

spring:
  application:
    name: grpc-web-client

grpc:
  client:
    greeterClient:  # This must match the bean name used in @GrpcClient
      address: static://localhost:58081  # gRPC server address
      negotiationType: PLAINTEXT  # Use TLS if needed (use "TLS" for secured communication)